### ISSUE TITLE
set_token_auth() doesn't seem to work

### ISSUE THREAD

**Issue by Ebsan** [samastur/matomo#1]
I'm trying to set the IP manually however the server says that authentication isn't working. When I'm setting the IP I make sure to set_token_auth() but the token doesn't seem to be get sent along with the request.

**Comment by Ebsan** [comment]
It looks like the auth is only set when bulk_requests are sent. However, when I try to do bulk_requests it never succeeds. It looks like the following line will always be hit if I'm reading it correctly:

https://github.com/samastur/matomo/blob/master/src/matomo/tracker.py#L749

**Comment by samastur** [comment]
Thank you for reporting this issue. It happens because Python's version of `sendRequest` method is a much simpler implementation of PHP's and this part along with some others got lost in translation.

I'm working on new release and hope to release it by the year end. I'll try to fix this in it, but patches are always welcome :)

**Comment by Ebsan** [comment]
Sounds good, thank you for looking into it. I put in a PR that should fix that check to look for a null storedRequests instead. I also added the authToken to data on POST sendRequests.
